services:
  bookwiki-frontend:
    image: bookwiki-frontend
    container_name: bookwiki-frontend
    build:
      context: ./bookwiki-frontend
      dockerfile: Dockerfile
      args:
        - BUILD_MODE=development
    ports:
      - "3000:3000"
    volumes:
      - ./bookwiki-frontend/src:/app/src

  books-service:
    build: books-service
    ports:
      - "8080:8080"
    hostname: books-service
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/auth-db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pwd


  mysql:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=auth-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./books-service/src/main/resources:/data.sql
      - ./books-service/src/main/resources:/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uuser", "-ppwd", "-h", "127.0.0.1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdmin
    links:
      - mysql
    restart: always
    ports:
      - 5013:80
    environment:
      - PMA_ARBITRARY=1