name: Deploy Dockerized Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bookwiki-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v3
        with:
          context: ./bookwiki-frontend
          file: ./bookwiki-frontend/Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bookwiki-frontend:latest

      - name: Deploy to Docker Swarm
        run: |
          docker service update --image ${{ secrets.DOCKER_USERNAME }}/bookwiki-backend:latest bookwiki_backend
          docker service update --image ${{ secrets.DOCKER_USERNAME }}/bookwiki-frontend:latest bookwiki_frontend