name: Deploy BookWiki

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: auth-db
          MYSQL_USER: user
          MYSQL_PASSWORD: pwd
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      - name: Run database migrations
        run: |
          docker exec -it books-service ./gradlew flywayMigrate

      - name: Wait for MySQL to be ready
        run: |
          until docker exec mysql mysqladmin ping --silent; do sleep 5; done

      - name: Deploy application
        run: |
          docker-compose up --build -d

      - name: Verify deployment
        run: |
          curl http://localhost:8080/health
